builds:
  - binary: hallonlarm
    main: .
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
      - 7
archive:
  files:
    - LICENSE
    - README.md
  format_overrides:
    - goos: windows
      format: zip
