---
language: go
sudo: false
notifications:
  email: false
jobs:
  fast_finish: true
  allow_failures:
    - go: master
  include:
    - stage: test
      go: 1.12.x
      install: go mod vendor
      script: go test -race -v $(go list ./... | grep -v /vendor/) 
      after_success:
        - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
